### ISSUE TITLE
Predict Point Tracks for the Selected Points in Online PyTorch TAPIR demo? 

### ISSUE THREAD

**Issue by weirenorweiren** [google-deepmind/tapnet#103]
Online PyTorch TAPIR demo misses the Select Any Points at Any Frame & Predict Point Tracks for the Selected Points code blocks. I am wondering that could Online PyTorch TAPIR demo also manage to predict point tracks for the selected points as Standard PyTorch TAPIR demo?

**Comment by yangyi02** [comment]
Hi @weirenorweiren , we just add the Select Any Points at Any Frame & Predict Point Tracks code blocks in the Online PyTorch TAPIR demo. Please take a look.

We are also working on fix the buggy Online PyTorch BootsTAPIR checkpoint currently. Thanks for your patience.

**Comment by yangyi02** [comment]
I will close this issue for now, unless you find something wrong.
