### ISSUE TITLE
Get Query Features in TAPIR

### ISSUE THREAD

**Issue by shivanimall** [google-deepmind/tapnet#105]
Is there a reason why the return value for `get_query_feats` is not supported in TAPIR as the value is already present in `interp_feats`?
https://github.com/google-deepmind/tapnet/blob/main/tapnet/torch/tapir_model.py#L174

**Comment by cdoersch** [comment]
This is a legacy parameter used to compute TAP-Net losses.  

If you want to get query features from TAPIR, you should directly call the `get_query_features()` method at https://github.com/google-deepmind/tapnet/blob/main/tapnet/torch/tapir_model.py#L216 .  This method is also exposed on the `ParameterizedTAPIR` object.  If you want to avoid recomputation, you can pass query features or feature grids into the `__call__` function.
