### ISSUE TITLE
Tapvid 3D size

### ISSUE THREAD

**Issue by npmhung** [google-deepmind/tapnet#110]
Could I ask how much disk space the Tapvid3D datasets occupy?

**Comment by skoppula** [comment]
Hey! All three components of the TAPVid-3D datasets occupy together 138GB on our machines. The breakdown:
- PStudio: 1 GB
- DriveTrack: 80GB
- ADT: 57GB

**Comment by Kou-99** [comment]
> Hey! All three components of the TAPVid-3D datasets occupy together 138GB on our machines. The breakdown:
> 
> * PStudio: 1 GB
> * DriveTrack: 80GB
> * ADT: 57GB

Hi, thanks for your valuable information! I'm currently in the process of downloading the ADT dataset as per the instructions in [README](https://github.com/google-deepmind/tapnet/blob/main/tapnet/tapvid3d/README.md). According to the README, I should first download the ADT dataset and then use generate_adt.py to download and generate the .npz files. However, when I checked the CDN JSON file from Project Aria Explorer, the 236 sequences from ADT, including compressed main_vrs, main_groundtruth, segmentation, and depth files, take up around 1.7TB. This size is significantly larger than the 57GB you mentioned. Could you please clarify if I have misunderstood anything? Thank you for your help in advance!

**Comment by ignacio-rocco** [comment]
Hi, after generating TAPVid3d you should be able to delete the source ADT
files. If you don't have enough space to download all of it at once, you
could modify the generation script to download one scene at a time, process
it, delete the sources and move to the next scene.

Best
Ignacio
