### ISSUE TITLE
Understading about annotation

### ISSUE THREAD

**Issue by dat-nguyenvn** [google-deepmind/tapnet#112]
You mention 
The points (float32 tensor with 3 axes; the first is point id, the second is time, and the third is x/y).

What is x/y here?  I read the pkl file, and the value looks like [0.41469392, 0.53467155]
so I guess, you are normalized it. 

x = position in horizon/width
y = position in vertical / height 

Am I correct?
Thanks 
Dat

**Comment by cdoersch** [comment]
Yes, what's stored in the pickle file is normalized.  As usual for image coordinates, 0,0 is the upper-left corner.

The reader re-normalizes these to actual pixel coordinates, i.e., multiplies by [width, height].
