### ISSUE TITLE
Clarification on Units in TAPVid-3D Dataset

### ISSUE THREAD

**Issue by RunsenXu** [google-deepmind/tapnet#117]
Hello,

First of all, thank you for the amazing work on this project!

I have a quick but important question: Are all the 3D point locations in the TAPVid-3D dataset represented in meters?

Thank you for your help!

Best regards,
Runsen

**Comment by skoppula** [comment]
Hi Runsen, yes, it should be meters.

**Comment by RunsenXu** [comment]
Nice. Thank you!
