### ISSUE TITLE
Missing video sequence for tapvid-kinetics

### ISSUE THREAD

**Issue by Kou-99** [google-deepmind/tapnet#121]
Hi, thanks for the great work!

When I try to create the tapvid-kinetics dataset from the csv file ([https://storage.googleapis.com/dm-tapnet/tapvid_kinetics.zip](https://storage.googleapis.com/dm-tapnet/tapvid_kinetics.zip)) , I find that there are 3 missing videos, namely BBSK3Wv0jXM, G4Z1Ug34B5I, pk1yi_HMsAI. These videos are also not in the annotation file ([https://s3.amazonaws.com/kinetics/700_2020/annotations/val.csv](https://s3.amazonaws.com/kinetics/700_2020/annotations/val.csv)) of k770_2020_val as well, so I guess this issue is not related to the error in download & extraction. 

Is this behavior normal? And is there a fix for that? Thanks for your help in advance!

**Comment by cdoersch** [comment]
Unfortunately Kinetics is subject to wipeout if users decide to take down some videos.  We expect that these removed videos will not be correlated with the score, so you should report numbers on whatever videos are available at the present date.  Note that the underlying Kinetics dataset operates in the same way.

**Comment by yangyi02** [comment]
Hi @Kou-99 , as Carl mentioned, it is normal Kinetics videos are wipeout. Luckily there are ~1000 videos, so missing a few may not affect performance significantly. I will close this issue for now. Thanks.
