### ISSUE TITLE
Tapet colab demo can't select points manually

### ISSUE THREAD

**Issue by Icecream-blue-sky** [google-deepmind/tapnet#123]
In https://colab.research.google.com/github/deepmind/tapnet/blob/master/colabs/tapir_demo.ipynb, run "Select Any Points at Any Frame" will output nothing. 
![image](https://github.com/user-attachments/assets/ff213520-9e8a-498e-ac42-f44e623faa30)
But in https://colab.research.google.com/github/deepmind/tapnet/blob/master/colabs/causal_tapir_demo.ipynb, it's normal.
![image](https://github.com/user-attachments/assets/995eadf0-362e-4170-9cb0-bf2a5254835a)
Why?

**Comment by yangyi02** [comment]
What if you remove the last line: `print(select_points)` in the first cell?

**Comment by Icecream-blue-sky** [comment]
> What if you remove the last line: `print(select_points)` in the first cell?

It results the same. The reason I added this is to see if the above code is executed.

**Comment by yangyi02** [comment]
Ok, I figure out the problem. Thanks for reporting the bug.

It is due to we add `matplotlib.use('Agg')` in the import cell. For your short term solution, please try comment this line and see if the select points interface jump out.

**Comment by yangyi02** [comment]
The [tapir_demo.ipynb](https://colab.research.google.com/github/deepmind/tapnet/blob/master/colabs/tapir_demo.ipynb), is updated, please try again see if the select points interface can work. 

Thanks.

**Comment by yangyi02** [comment]
Thanks again for reporting the issue. @Icecream-blue-sky  All the colab demos are recently tested and selecting points manually should now back to work. Please try again. I will close this issue for now.
