### ISSUE TITLE
What the difference between Standard TAPIR and Online TAPIR ?

### ISSUE THREAD

**Issue by Icecream-blue-sky** [google-deepmind/tapnet#124]
Is the former model offline track ?

**Comment by yangyi02** [comment]
Right, Standard TAPIR conduct temporal convolution on all frames (including future frames) to predict point location at every frame. While Online TAPIR replaces the temporal convolutions with similarly-shaped causal convolutions, such that the activation of each unit at time t depends only on the activations from times ≤ t.
