### ISSUE TITLE
Panning MOVi-E

### ISSUE THREAD

**Issue by hkchengrex** [google-deepmind/tapnet#29]
Hi, 

Thank you for the great work and code release. May I know how should I obtain "panning MOVi-E" in the TAPIR paper? I see references in this repo to the standard Kubric API but I don't see any pointers to the "panning" version.

Thanks a lot!

**Comment by cdoersch** [comment]
Hi, we're still working on a release for this.  Assuming our ICCV submission is accepted, it will be released before the conference.

**Comment by troveski** [comment]
Given that the paper was accepted by ICCV, is there any update on this issue?

**Comment by ret-1** [comment]
I have noticed this update: https://github.com/google-research/kubric/tree/main/challenges/movi#movi-e

**Comment by cdoersch** [comment]
The generation scripts were released a long time ago; closing this issue.
