### ISSUE TITLE
AttributeError: module 'jax.numpy' has no attribute 'DeviceArray'

### ISSUE THREAD

**Issue by ernestchu** [google-deepmind/tapnet#41]
In jax 0.4.14, `jax.numpy.DeviceArrary` is deprecated, see
https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-14-july-27-2023

This makes your code produce the error in the title

**Comment by cdoersch** [comment]
I don't think we have any calls to DeviceArray in our code.  Can you provide a full stacktrace?  It's possible that you're depending on an obsolete version of a dependency.

**Comment by ernestchu** [comment]
Okay, I think the problem is in `jaxline`. I've also opened an issue there: deepmind/jaxline#15

**Comment by ZhaoqunZhong** [comment]
I ran into the same problem when trying out this part from the README. But the live camera demo worked fine.
<img width="827" alt="Screenshot 2023-09-02 at 20 55 54" src="https://github.com/deepmind/tapnet/assets/44191501/6b5d42b1-6529-4bc3-b4b0-81c46e321a9e">

**Comment by bhack** [comment]
I've a local patch but `jaxline` seems unmaintained so I don't know whether it is worth wasting time to prepare a PR

**Comment by yangyi02** [comment]
The external github jaxline is not maintained which makes it hard. When we ran the eval_inference, we use an old jax of version 0.4.12.

For now, please follow the live demo as an example for model inference, we will update the README file accordingly.

**Comment by cdoersch** [comment]
Jaxline is widely used and well-maintained inside of DeepMind, although the internal version is somewhat different.  How  complicated is the patch that makes it work?  If it's straightforward, I can potentially find someone to merge the change.

**Comment by bhack** [comment]
@cdoersch It is quite minimal if there is a chance to review It I can run OSS tests and submit it. Is there an acrtive CI in the OSS repo?

**Comment by bhack** [comment]
@cdoersch In the meantime https://github.com/deepmind/jaxline/pull/16

**Comment by cdoersch** [comment]
Thanks for this.  I reached out to the Jaxline maintainers, and it turns out that this was fixed internally a while ago. They're hoping to push to Github soon, but not sure exactly when.

**Comment by cdoersch** [comment]
Cool, this should be fixed as a part of https://github.com/deepmind/jaxline/commit/cde8d1e5bc7212aebef2a52d15a19ca09f0a2ec6
