### ISSUE TITLE
inference time as a function of point number and frame number

### ISSUE THREAD

**Issue by CHYjeremy** [google-deepmind/tapnet#47]
HI authors of TAPIR,

Thanks again for your work.

I open this issue because i would like to know how the inference time change with respect to point and frame number.

Does the time goes up linearly w.r.t these two argument, or what other form of dependence?

I tried experimenting with it but my result varies a little from time to time, so i asked.

thanks~

**Comment by yangyi02** [comment]
Please find our study of inference time at Table 9 in the paper. https://arxiv.org/pdf/2306.08637.pdf

In the table, we limit our setup to maximum to 50 frames and 50 points. Inference time grows w.r.t. point and frame number but not exactly linear from our observation (we ran 10 times for each setup and average). The utilization of GPU allows the model to parallel compute feature maps and run iterative updates on multiple points simultaneously.

Inference time also grows with video resolution.

<img width="488" alt="Screenshot 2023-08-19 at 10 32 24 AM" src="https://github.com/deepmind/tapnet/assets/4534987/15f6a8ac-234f-4f8a-923e-f650d3adf3d5">
