### ISSUE TITLE
CPU compile live_demo

### ISSUE THREAD

**Issue by bhack** [google-deepmind/tapnet#53]
```
E external/xla/xla/service/slow_operation_alarm.cc:65] 
********************************
[Compiling module jit_apply_fn] Very slow compile? If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
********************************
E external/xla/xla/service/slow_operation_alarm.cc:133] The operation took 9m29.906265931s

********************************
[Compiling module jit_apply_fn] Very slow compile? If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
********************************

```
I was just trying to run `live_demo.py` on CPU and I got these messages.
How much time the compilation time it requires?

**Comment by bhack** [comment]
What is the current coverage of this on different device types?
```
from jax.experimental.compilation_cache import compilation_cache as cc

```

**Comment by cdoersch** [comment]
TAPIR compilation often takes minutes on GPU.  This is an unfortunate limitation of JAX: large graphs take a long time to compile.  We don't have immediate plans to simplify the graph (it would be another entire paper), so if this is a problem for you, I'd suggest you raise an issue with the JAX team.

That said, 10 minutes seems a bit excessive (I think in my experiments, I was seeing more like 5 minutes to compile).  I'm not sure what can cause that kind of discrepancy; it might have to do with CPU model, but I doubt that's very helpful to you.

**Comment by bhack** [comment]
Do we have different levels of components compilation? E.g. the live demo it seems to me most demanding

**Comment by cdoersch** [comment]
Not currently.  I'd like to optimize this better, but I'm not very familiar with how compilation_cache works.

From what I can find, jax compilation_cache now seems supported on GPU.  We might be able to distribute a compilation cache for the live demo, but I'm not sure we have the bandwidth for it.  This is more intended for research than production currently.

**Comment by bhack** [comment]
Ok thanks
