### ISSUE TITLE
Longest video input possible

### ISSUE THREAD

**Issue by Jeremycccc** [google-deepmind/tapnet#56]
Hi authors of tapir,

Great thanks for your great work.

I would like to know, what is the longest video( i.e. largest frame number) that tapir model can stand up with without cuda running out of memory? for example, i have tried with a video with 400 frames and it works fine but it exploded with a video of 500 frames.

(i think it has nothing to do with resolution since it's resized to (256,256) after put into model, i think it has something to do with number of gpu number? do we simply put more gpu and it works fine? could you roughly give a number of frame if i have three 4090s available?)

bear me with this long question~ thanks a lot!

**Comment by cdoersch** [comment]
If you need to work with very long videos, I'd suggest you work with the causal model, which is designed to run online; then you can pass one frame at a time and the memory usage won't grow with the number of frames.  Note that you can also break videos into clips and use query features from one clip on another clip.

For a 16GB GPU, maxing out at 400 frames at 256x256 sounds reasonable.  However, note that parts of the model are also proportional to the number of points, so you may be able to push it slightly farther by querying fewer points.

The public code is does not support model sharding across multiple GPUs; our internal code for this depends on internal DeepMind frameworks that unfortunately can't be released.
