### ISSUE TITLE
Errors when generating TAP-kinetics

### ISSUE THREAD

**Issue by Jeremycccc** [google-deepmind/tapnet#57]
I encounter the following error when following the guide to generate TAP_kinetics,

I execute "python3 generate_tapvid.py..." as guided but the following error pops out:
```
Traceback (most recent call last):) 
  File "/home/hychen/tapnet/data/generate_tapvid.py", line 236, in <module>
    app.run(main)
  File "/home/hychen/anaconda3/envs/tap-kine/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/hychen/anaconda3/envs/tap-kine/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/hychen/tapnet/data/generate_tapvid.py", line 223, in main
    data.append(generate_example(video))
  File "/home/hychen/tapnet/data/generate_tapvid.py", line 162, in generate_example
    imgs_encoded = extract_frames(video.video_path, 25.0)
  File "/home/hychen/tapnet/data/generate_tapvid.py", line 152, in extract_frames
    jpeg_bytes, _ = cmd.run(capture_stdout=True, quiet=True)
  File "/home/hychen/anaconda3/envs/tap-kine/lib/python3.9/site-packages/ffmpeg/_run.py", line 313, in run
    process = run_async(
  File "/home/hychen/anaconda3/envs/tap-kine/lib/python3.9/site-packages/ffmpeg/_run.py", line 284, in run_async
    return subprocess.Popen(
  File "/home/hychen/anaconda3/envs/tap-kine/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/hychen/anaconda3/envs/tap-kine/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
```

I was doing it in a seperate conda environment, It seems that the error pops when executing subprocess.py, it doesn't find 'ffmpeg'. But 
```
ffmpeg             
ffmpeg-python  
```
all exist in this anaconda env, may i ask where does it go wrong?

**Comment by Jeremycccc** [comment]
I notice problem is that $PATH does not contain the folder path that include ffmpeg.

However, after i include the path, 
```
PermissionError: [Errno 13] Permission denied: 'ffmpeg'
```
pops out, so i "chmod +x/chmod 755" on ffmpeg, but none of it works, the same error pertains.

**Comment by yangyi02** [comment]
Please check these two threads if they are helpful:
https://github.com/kkroening/ffmpeg-python/issues/251
https://stackoverflow.com/questions/29454002/filenotfounderror-errno-2-no-such-file-or-directory-ffmpeg

One possible reason is your system has not installed ffmpeg, so please try `sudo apt install ffmpeg`.

**Comment by Jeremycccc** [comment]
Hi Yi, thanks for your suggestion, i have asked the admin to apt install ffmpeg,

however, i still am curious that,
 i have "pip install ffmpeg" and modified the environment variable so that "ffmpeg" is seen by the environment, but it shows "PermissionError" as i posted above.

What is the reason for this and why "sudo apt install" ffmpeg to the public bin would help with this?

**Comment by yangyi02** [comment]
Maybe this thread answers your question?
https://stackoverflow.com/questions/62470863/ffmpeg-command-not-found-but-pip-list-shows-ffmpeg


pip install ffmpeg installs a [Python package](https://pypi.org/project/ffmpeg/) that doesn't have any executable scripts; it's for calling functions from Python code.

If you want to install ffmpeg program you need to run — what do you use, Ubuntu? — sudo apt install ffmpeg

The Python package requires the program anyway.

**Comment by Jeremycccc** [comment]
Thanks a lot Yi! Your explanation is both clear and precise!

It works fine now: ten pickle files representing around 1000 videos. However, for my personal reason, we would actually like it  to be 1000 mp4 videos or any kinds of data format each contains/represents a video. How would you think is the appropriate way to do so, either from these 10 pickle file or any other way?

Thanks again

**Comment by Jeremycccc** [comment]
I have managed to accomplish it writing some code.

Thank you Yi!

I shall now close this issue
