### ISSUE TITLE
Visualization 

### ISSUE THREAD

**Issue by xxiMiaxx** [google-deepmind/tapnet#62]
Dear Authors, thank you for this brilliant work. 

I noticed at TAPIR website you have the following visualizations:

![image](https://github.com/google-deepmind/tapnet/assets/24461701/b8df8663-cbb4-4edd-8fe2-b9575615c6c5)

you mentioned that you have obtained it by segmenting the scene into foreground and background, then you removed the background points to reveal how the objects are moving through a scene. 

I was wondering is the script/function that performs that available in the repo?  

I just think that this particular visualization will deliver a stronger point on my videos.

Thank you. 

best,
Mia

**Comment by cdoersch** [comment]
This code is now released!  See https://colab.research.google.com/github/deepmind/tapnet/blob/master/colabs/tapir_rainbow_demo.ipynb and let me know if it works for you.

**Comment by cdoersch** [comment]
No one has reported further issues, so I'm closing this.
