### ISSUE TITLE
About Dataset Download

### ISSUE THREAD

**Issue by wwsource** [google-deepmind/tapnet#67]
Nice work!
Could you share the videos of Davis, Kinetics, and Stacking? Many links you shared have become invalid. 
Many thanks!

**Comment by cdoersch** [comment]
Which link is broken?  I just tried the link for the DAVIS .zip file in the main github README and it worked fine.

**Comment by wwsource** [comment]
I am referring to Davis' video links, such as the video “classic-car” with the unavailable link https://www.youtube.com/watch?v=EuX_NCNHYK0.

**Comment by cdoersch** [comment]
DAVIS is available through the davis dataset website: https://davischallenge.org/ .  Our downloadable archive also contains a copy of the dataset, although it's at relatively low resolution.

The original stacking videos are included in our archives.  

We don't maintain the Kinetics videos in this repository, only the point tracks; you will need to refer to other sources (e.g. the activitynet challenge) to find out how to download them.  If some videos have become unavailable, it's still OK to evaluate without them.
