### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by Setarekhosravi** [google-deepmind/tapnet#68]
I want to train tapnet on my own dataset. I have two questions, first, what is the training pipeline? and can I train tapnet on my own dataset?
thank you.

**Comment by cdoersch** [comment]
Training is supported, although it's quite resource-intensive.  See here: https://github.com/google-deepmind/tapnet#tap-net-and-tapir-training-and-inference

You can certainly train on your own dataset.  See here for the format that the kubric loader returns: https://github.com/google-research/kubric/blob/main/challenges/point_tracking/dataset.py#L780 .

**Comment by Setarekhosravi** [comment]
@cdoersch Thank you.
