### ISSUE TITLE
How many pixels are you tracking in live_demo.py? 

### ISSUE THREAD

**Issue by weirenorweiren** [google-deepmind/tapnet#69]
How many pixels are you tracking to make the statement that "In our tests, we achieved ~17 fps on 480x480 images on a quadro RTX 4000. "?

**Comment by weirenorweiren** [comment]
Another relevant question is that what's the memory used for your experiments? Does it have an impact on the live tracking performance?

**Comment by weirenorweiren** [comment]
👀

**Comment by cdoersch** [comment]
I believe that's with the default live_demo.py -- by default it tracks 8 points. It is unfortunately difficult to calculate memory constraints, as JAX tends to allocate much more memory than it actually needs.  However, I recall that I was still able to run live_demo.py when I limited the GPU memory footprint to 1GB.
