### ISSUE TITLE
About weird tracking results compared to robotap

### ISSUE THREAD

**Issue by YunchuZhang** [google-deepmind/tapnet#73]
Hi there,
Thanks for sharing and open souring the good research!
0. I tried the tapir model on a test set with boxes, it works relatively well (when there's no occlusions)

https://github.com/google-deepmind/tapnet/assets/33641269/4d1129af-d8cf-4e22-bcf1-9e2ba912cfaf

2. I tried to use the tapnet model for real world point tracking and found that I could not get the same result as shown in robotap on regular cubes(no textures) as shown here:

https://github.com/google-deepmind/tapnet/assets/33641269/917c6445-3b8e-49b2-a7aa-8a1c3edb67a3

3.  when object has textures and the tracking will be missed up when it is turned over 90 degrees 

https://github.com/google-deepmind/tapnet/assets/33641269/a744b463-9b49-45c4-937e-5281b7dc660f

https://github.com/google-deepmind/tapnet/assets/33641269/df9fb95c-180d-4635-b1d4-f14724b9b9b0

I just follow the live_demo.py script to get those results, do you have any clues on how to potentially improve the tracking perfermance?

Thanks

**Comment by cdoersch** [comment]
Indeed, textureless objects and large rotations/scale changes are known weaknesses with the existing TAP approaches.  We expect future research will address these, but the entire field has only been pursued for a couple of years now.  This is part of the reason we did the clustering: with the clustering code, you can often discover sets of query points that are on the same object, so you won't lose the whole object even if you've lost a few points.  

It should also, in theory, be possible to do smarter search across multiple scales or rotations, although this hasn't been researched well yet.

**Comment by YunchuZhang** [comment]
Thanks for the detailed explanation and appreciated for that!
We will try with clustering as you suggested.
