### ISSUE TITLE
robotap's query points selection question

### ISSUE THREAD

**Issue by nutsintheshell** [google-deepmind/tapnet#82]
the robotap article shows a good way to use points tracked by the tapir. however, I don't find the part that shows how to make sure points across demos mean the same point on the object. how do we know two different pionts in pixel space in two different demos mean the same point on the physical object?
Additional, because we need to track trajectories. We have to know which trajectory a point should track. We should match the point to a trajectory. I wonder how this is achieved.
It would be appreciated if someone tells me.

**Comment by cdoersch** [comment]
We don't.  TAPIR identifies points based on appearance; it's trained on synthetic kubric data which does not have duplicate objects, so the algorithm tends to assume that similar-looking objects are, in fact, the same.  This is useful for RoboTAP in our current setting, although the more general problem of dealing with similar-looking objects within the same scene is unsolved.  TAPIR is likely to have false-positives in these cases.

**Comment by nutsintheshell** [comment]
Do you mean that we offer each point a point id and for points in different demos we match points that have the same id?do you think my understand is right?

**Comment by nutsintheshell** [comment]
> We don't. TAPIR identifies points based on appearance; it's trained on synthetic kubric data which does not have duplicate objects, so the algorithm tends to assume that similar-looking objects are, in fact, the same. This is useful for RoboTAP in our current setting, although the more general problem of dealing with similar-looking objects within the same scene is unsolved. TAPIR is likely to have false-positives in these cases.

Do you mean that we offer each point a point id and for points in different demos we match points that have the same id?do you think my understand is right?

**Comment by nutsintheshell** [comment]
Maybe my expression is wrong. My problem is, how do we select the points to be tracked. Is the points in the demos randomly selected?in the following demo and the test time, the upper demo shows three trajectories.the point in the lower image need to choose only one trajectory to track.I wonder how we select the trajectory.
![IMG_20240227_161542](https://github.com/google-deepmind/tapnet/assets/110964890/ab42b9d7-1858-49dc-98da-f5601b185a89)

![IMG_20240227_162103](https://github.com/google-deepmind/tapnet/assets/110964890/f097df25-9c65-4e95-86ef-886336fe5c77)

**Comment by cdoersch** [comment]
I don't understand what you're asking.  We have an entire section in the RoboTAP paper on how we select the points that we track at test time.  

Each point is represented by a descriptor, which is the output of get_query_features() from the online model.  These points are initially sampled randomly and then chosen based on their motion patterns in the demos.  We can extract query features from any image and then track the same point on the same object in any new video.
