### ISSUE TITLE
Pretrained Weights for  Pytorch Version of Online Tapir/BootsTapir

### ISSUE THREAD

**Issue by kumar-sanjeeev** [google-deepmind/tapnet#88]
Could you please upload the pretrained weights for the PyTorch version of online Tapir/BootsTapir, if available? or could you recommend how we can utilize the PyTorch implementation of Tapir/BootsTapir in an online fashion with the given pretrained weights (PyTorch) of Tapir/BootsTapir?

**Comment by cdoersch** [comment]
Sorry, we are still working on these!  It will probably be another few weeks before we are ready to release them.

**Comment by bhack** [comment]
Do you have any example of the Online Tapir/BootsTapir inference?

**Comment by cdoersch** [comment]
We now have a colab for this:

https://github.com/google-deepmind/tapnet/blob/main/colabs/torch_causal_tapir_demo.ipynb
