### ISSUE TITLE
pytorch version TAPIR 's training file

### ISSUE THREAD

**Issue by pubyLu** [google-deepmind/tapnet#95]
can you release train Tapir pytorch .py files?

**Comment by cdoersch** [comment]
Sorry, we don't currently have the bandwidth to port our tapir training code over to pytorch and properly test it.  All of our current development is still in JAX.

**Comment by yangyi02** [comment]
I will close it now since we are not planning to implement pytorch training for TAPIR so far. We may re-open if there is indeed a version.

We also welcome pytorch implementation of TAPIR training from external world. Thanks.
