### ISSUE TITLE
Annotation Tool for TAP-VID

### ISSUE THREAD

**Issue by aetaffe** [google-deepmind/tapnet#96]
Hello,

I am working on creating a dataset similar to TAP-VID but composed of surgical videos, is the tool used to annotate the videos in TAP-VID available for use?

**Comment by yangyi02** [comment]
Hi aetaffe,

The annotation tool is used internally and is not released to public. 

However, we provide a colab notebook that illustrates how to use optical flow to assist the human annotation: https://github.com/google-deepmind/tapnet/blob/main/colabs/optical_flow_track_assist.ipynb

Hope it can help you a little bit.

**Comment by aetaffe** [comment]
Thank does help! Thank you!

**Comment by aetaffe** [comment]
Thank you! That does help!
