### ISSUE TITLE
TAPIR PyTorch checkpoint size mismatch with model

### ISSUE THREAD

**Issue by shivanimall** [google-deepmind/tapnet#97]
Hello,

I am loading the Tapir PyTorch model from the checkpoint on the README. No changes to the TAPIR PyTorch model code. 

Receive this error:

`
  File "/users/shivanim/anaconda3/envs/tapir/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TAPIR:
	size mismatch for torch_pips_mixer.linear.weight: copying a param with shape torch.Size([512, 486]) from checkpoint, the shape in current model is torch.Size([512, 535]).`

**Comment by shivanimall** [comment]
#70 helped, maybe you can add to the README

**Comment by shivanimall** [comment]
https://github.com/google-deepmind/tapnet/issues/70#issuecomment-2145642013

**Comment by cdoersch** [comment]
Some models have 2 levels, others have a third level which is at stride 16, and is just an average pool of the second layer.  In practice, this makes only a very small difference in performance (the stride 4 feature, however, is essential for good performance).

**Comment by shivanimall** [comment]
Thanks Carl and Yi for the clarifications, that helps!

**Comment by yangyi02** [comment]
Thank you. We will close this issue now.
